version: '3.8'
networks:
    video:
        external: true
services:
    mongo:
      image: mongo
      restart: always
      hostname: mongo
      container_name: mongo
      volumes:
          - /mnt/files/data/mongo/:/data/db
      network_mode: host
    mongo-express:
        image: mongo-express
        container_name: mongo-express
        hostname: mongo-express
        environment:
            ME_CONFIG_MONGODB_SERVER: localhost
        network_mode: host
        ports:
            - 8081:8081
    queue_processor:
        container_name: queue_processor
        hostname: queue_processor
        build: ./queue_processor
        restart: always
        volumes: 
            - /mnt/files/share/video:/mnt/files/share/video
            - /mnt/files/data/queue_processor/logs:/queue_processor_logs
        network_mode: host
    sync_video:
        container_name: sync_video
        build: ./sync_video/
        restart: always
        network_mode: host
        ports: 
            - 8080:8080
networks:
    video:
        external: true
networks:
    video:
