version: '3.8'
services:
    mongo:
      image: mongo
      restart: always
    mongo-express:
        image: mongo-express
        ports:
            - 8081:8081
    video:
        build: .
        ports: 
            - 8080:8080
        volumes:
            - /mnt/files/share/video
    queue_processor:
        build: ./queue_processor
        ports: 
            - 27017:27017
